### ISSUE TITLE
How to assign People

### ISSUE THREAD

**Issue by philschulz** [philschulz/VITutorial#3]
This is an example issue that is opened to demonstrate assignment of issues and reviews. To the right their is a toolbar where one can select Assignees (people who should resolve the issue). When post pull request in the same toolbar there is the additional option of assigning reviewers.

The main reason to open issues is to
a) suggest improvements that cannot be implemented immediately but should be implemented
in the future
b) address decisions/questions about the project that cannot be covered in pull request (i.e. that are not directly related to tex or code).

**Comment by wilkeraziz** [comment]
I get it :)

**Comment by AnjumMomin** [comment]
can u solve may problem??
