### ISSUE TITLE
Beamer style

### ISSUE THREAD

**Issue by philschulz** [philschulz/VITutorial#4]
We have to decide on a beamer layout before we start working on the slides. Have a look [here](https://hartwork.org/beamer-theme-matrix/). I would vote for either Boadilla with beaver or Montpellier with beaver.

**Comment by wilkeraziz** [comment]
I like Boadilla's progress bar (at the bottom) over Montpellier's (which looks like a tree structure at the top), but itemize and enumerate look much better in Montpellier. Should we start with Montpellier then? If the progress bar turns out too annoying/distracting we can reassess this.

**Comment by philschulz** [comment]
Alright, let's go for Montpellier with beaver then. We could probably just copy past the code for the progress bar from Boadilla if needed.
